export const PWA_CACHE_PREFIX = 'planet-engineering-fleet';
export const PWA_CACHE_VERSION = 'v2-5c3fa8079b0844e0cf36584a17b20f3eb7220c6083676ecfef266b9e665e5005';

export const PWA_ASSETS = Object.freeze([
  './',
  './index.html',
  './styles.css',
  './manifest.webmanifest',
  './service-worker.js',
  './pwa-assets.js',
  './src/app.js',
  './src/audio.js',
  './src/answer-effects.js',
  './src/content.js',
  './src/course-table.js',
  './src/curriculum/chinese.js',
  './src/curriculum/english.js',
  './src/curriculum/index.js',
  './src/curriculum/lessons.js',
  './src/curriculum/math.js',
  './src/curriculum/projects.js',
  './src/curriculum/regions.js',
  './src/curriculum/schema.js',
  './src/game-core.js',
  './src/honors.js',
  './src/mastery.js',
  './src/parent-actions.js',
  './src/preferences.js',
  './src/progression.js',
  './src/question-factories.js',
  './src/register-service-worker.js',
  './src/scene-model.js',
  './src/storage.js',
  './src/view-model.js',
  './src/views/completion-view.js',
  './src/views/course-table-view.js',
  './src/views/garage-view.js',
  './src/views/icons.js',
  './src/views/lesson-view.js',
  './src/views/map-view.js',
  './src/views/placement-view.js',
  './assets/construction-fleet.svg',
  './assets/region-scenes.svg',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/icon-maskable-512.png',
  './assets/icons/apple-touch-icon-180.png',
]);
