export const PWA_CACHE_PREFIX = 'planet-engineering-fleet';
export const PWA_CACHE_VERSION = 'v2-0b0404efcb6baf9ea25a841c2e891991c6e0d7fd434d175f9e1e614b6d3d079c';

export const PWA_ASSETS = Object.freeze([
  './',
  './index.html',
  './styles.css',
  './manifest.webmanifest',
  './service-worker.js',
  './pwa-assets.js',
  './src/app.js',
  './src/audio.js',
  './src/content.js',
  './src/course-table.js',
  './src/curriculum/chinese.js',
  './src/curriculum/english.js',
  './src/curriculum/index.js',
  './src/curriculum/lessons.js',
  './src/curriculum/math.js',
  './src/curriculum/projects.js',
  './src/curriculum/regions.js',
  './src/curriculum/schema.js',
  './src/game-core.js',
  './src/honors.js',
  './src/mastery.js',
  './src/parent-actions.js',
  './src/progression.js',
  './src/question-factories.js',
  './src/register-service-worker.js',
  './src/scene-model.js',
  './src/storage.js',
  './src/view-model.js',
  './src/views/completion-view.js',
  './src/views/course-table-view.js',
  './src/views/garage-view.js',
  './src/views/icons.js',
  './src/views/lesson-view.js',
  './src/views/map-view.js',
  './src/views/placement-view.js',
  './assets/construction-fleet.svg',
  './assets/region-scenes.svg',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/icon-maskable-512.png',
  './assets/icons/apple-touch-icon-180.png',
]);
